### ISSUE TITLE
The ability to specify a multi-tenant environment where cluster-wide permissions aren't assumed

### ISSUE THREAD

**Issue by gadekishore** [elastic/eck-diagnostics#120]
In a secured multi-tenant Kubernetes environments where operators generally do not have cluster-wide access so generating ECK diagnostics are really painful in few circumstances due to the permissions.

For example, cluster level diagnostics are captured using `--run-stack-diagnostics` flag within ECK diagnostic. The diagnostic pods get created, but never run because of a failed readiness probe.

To overcome this can we enhance ECK diagnostics with below:

1. The ability to specify a multi-tenant environment where cluster-wide permissions aren't assumed, so things like clusterrolebindings and nodes aren't gathered.

2. The ability to modify the stack-diagnostic pods to work in the same multi-tenant environment where root access isn't assumed.

**Comment by thbkrkr** [comment]
> The ability to specify a multi-tenant environment where cluster-wide permissions aren't assumed, so things like clusterrolebindings and nodes aren't gathered.

I'm not sure to understand what's problematic with the current behaviour. Without permissions, data is not collected and an entry is added to the `eck-diagnostic-errors.txt` file. Example:
```
clusterrolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:default:test-sa" cannot list resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope
nodes is forbidden: User "system:serviceaccount:default:test-sa" cannot list resource "nodes" in API group "" at the cluster scope
```

> The ability to modify the stack-diagnostic pods to work in the same multi-tenant environment where root access isn't assumed.

Yes, if I'm not mistaken, we should even be able to always run the support-diagnostics container without root privilege.



<details>
<summary>
POC pod.yml
</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: elastic-support-diagnostics
spec:
  containers:
  - name: main
    image: docker.elastic.co/eck-dev/support-diagnostics:8.2.8
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
    command: ["sh", "-c"]
    args:
      - |
        cd /out
        /support-diagnostics/diagnostics.sh -h hi-es-http --type api --bypassDiagVerify -u elastic --passwordText $ES_PW -s --noVerify -o .
        touch ready
        while true; do sleep 1; done;
    readinessProbe:
      exec:
        command:
          - cat
          - /out/ready
    env:
    - name: ES_PW
      valueFrom:
        secretKeyRef:
          name: hi-es-elastic-user
          key: elastic
    volumeMounts:
    - mountPath: /out
      name: output
  volumes:
  - name: output
    emptyDir: {}
```

```diff
diff --git a/internal/job.tpl.yml b/internal/job.tpl.yml
index a5c7dc0..70020bc 100644
--- a/internal/job.tpl.yml
+++ b/internal/job.tpl.yml
@@ -12,6 +12,9 @@ spec:
     - name: {{ .MainContainerName }}
       image: {{ .DiagnosticImage }}
       imagePullPolicy: IfNotPresent
+      securityContext:
+        runAsUser: 1000
+        allowPrivilegeEscalation: false
       env:
         - name: ES_PW
           valueFrom:
@@ -24,14 +27,15 @@ spec:
       command: [sh, -c]
       args:
         - |
-          ./diagnostics.sh -h {{.SVCName}} --type {{.Type}} --bypassDiagVerify -u elastic --passwordText $ES_PW {{if .TLS}}-s --noVerify{{end}} -o {{ .OutputDir }}
-          touch /ready
+          cd {{ .OutputDir }}
+          /support-diagnostics/diagnostics.sh -h {{.SVCName}} --type {{.Type}} --bypassDiagVerify -u elastic --passwordText $ES_PW {{if .TLS}}-s --noVerify{{end}} -o .
+          touch ready
           while true; do sleep 1; done;
       readinessProbe:
         exec:
           command:
             - cat
-            - /ready
+            - {{ .OutputDir }}/ready
       resources:
         requests:
           memory: 20Mi
```

</details>
</summary>
